### ISSUE TITLE
Begin elemental combination system

### ISSUE THREAD

**Issue by Wright-Dj** [CSCI150Team12/Elemental-Game#4]

**Comment by Wright-Dj** [comment]
We should design this so that adding a new element to the game is very easy.

**Comment by Robertor28** [comment]
Attached are some graphics displaying the amount of unique spells based solely on a few elements. It is rough around the edges, but I figured its purpose is only to understand how many spells would need to be made.

**Comment by Robertor28** [comment]
Had to do some editing, will attach matlab code if you are interested (though it is very rough so maybe ask for an explanation). 
![basic2](https://user-images.githubusercontent.com/43051356/45798840-39f46380-bc60-11e8-89a2-7949a85650fb.jpg)
![basic3](https://user-images.githubusercontent.com/43051356/45798842-3a8cfa00-bc60-11e8-8f8c-5e3d4e872f1b.jpg)
![basic4](https://user-images.githubusercontent.com/43051356/45798843-3b259080-bc60-11e8-81db-b50436d12ffe.jpg)
![basic5](https://user-images.githubusercontent.com/43051356/45798844-3c56bd80-bc60-11e8-9ee0-d6f8e7c4c73a.jpg)

[element_tracker.pdf](https://github.com/CSCI150Team12/Elemental-Game/files/2401646/element_tracker.pdf)
