### ISSUE TITLE
Begin element collection system

### ISSUE THREAD

**Issue by Wright-Dj** [CSCI150Team12/Elemental-Game#7]
Start with base elements. Other elements are collected from the environment.

**Comment by Wright-Dj** [comment]
If we make a voxel-based stage / environment, the elements could be collected directly from the environment.

**Comment by RussellSchellenberg** [comment]
Have two potions and a prototype of the Black hole Spell. Will need to finalize the black hole spell, by making it so it doesnt explode, to just continue moving.

**Comment by RussellSchellenberg** [comment]
Will need to make the collectables re-spawn, and make it so the user can only cast the collectable spells once.
